### ISSUE TITLE
Hi, Dev. Resolve This Feature Please.

### ISSUE THREAD

**Issue by ragibrawnak** [SJMormo/28-pin-matcher#1]
Always Showing "3 try left" But The Chances Left, Not Decreasing After Giving A Wrong Input.
 
![Screenshot 2022-05-07 004531](https://user-images.githubusercontent.com/104393199/167199340-7e96c285-4a6e-4d50-914f-d60aee34a460.png)

Please Resolve This ASAP, I Want To Copy Your Code xD.

**Comment by SJMormo** [comment]
Thank you. I will try to fix this as soon as possible.

**Comment by SJMormo** [comment]
Problem has been fixed. Let me know if you face any more problem.
